[project]
name = "emby-webhooks-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.118.0",
    "jinja2>=3.1.6",
    "uvicorn>=0.37.0",
]
